# Import Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer

# Import Dataset

In [2]:
dataset = pd.read_csv(r'E:\PYTHONCLASSJUPYTER\PrakashSenapati\Sklearn_Preprocessing.csv')

In [3]:
dataset.shape

(10, 4)

In [4]:
dataset.head()

State   Age   Salary Purchased
0     Mumbai  44.0  72000.0        No
1  Bangalore  27.0  48000.0       Yes
2  Hyderabad  30.0  54000.0        No
3  Bangalore  38.0  61000.0        No
4  Hyderabad  40.0      NaN       Yes

# Divide Dataset, iloc[]

* Dataset has been divided into Independent(x) & Dependent(y) variables

In [6]:
x = dataset.iloc[:, :-1].values
print(x)

[['Mumbai' 44.0 72000.0]
 ['Bangalore' 27.0 48000.0]
 ['Hyderabad' 30.0 54000.0]
 ['Bangalore' 38.0 61000.0]
 ['Hyderabad' 40.0 nan]
 ['Mumbai' 35.0 58000.0]
 ['Bangalore' nan 52000.0]
 ['Mumbai' 48.0 79000.0]
 ['Hyderabad' 50.0 83000.0]
 ['Mumbai' 37.0 67000.0]]


In [11]:
print(x[:,1:3])

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


In [7]:
y = dataset.iloc[:,3].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# SimpleImputer(), fit(), transform()

In [12]:
imputer = SimpleImputer()

In [14]:
imputer = imputer.fit(x[:,1:3])
imputer

SimpleImputer()

In [15]:
x[:,1:3] = imputer.transform(x[:,1:3])
x[:,1:3]

array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, 63777.77777777778],
       [35.0, 58000.0],
       [38.77777777777778, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

# LabelEncoder() & fit_transform()

In [17]:
labelencoder_x = LabelEncoder()
labelencoder_x

LabelEncoder()

In [18]:
x[:,0]

array(['Mumbai', 'Bangalore', 'Hyderabad', 'Bangalore', 'Hyderabad',
       'Mumbai', 'Bangalore', 'Mumbai', 'Hyderabad', 'Mumbai'],
      dtype=object)

In [19]:
labelencoder_x.fit_transform(x[:,0])

array([2, 0, 1, 0, 1, 2, 0, 2, 1, 2])

In [24]:
x[:,0] = labelencoder_x.fit_transform(x[:,0])
print(x[:,0])

[2 0 1 0 1 2 0 2 1 2]


In [23]:
print(x)

[[2 44.0 72000.0]
 [0 27.0 48000.0]
 [1 30.0 54000.0]
 [0 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [2 35.0 58000.0]
 [0 38.77777777777778 52000.0]
 [2 48.0 79000.0]
 [1 50.0 83000.0]
 [2 37.0 67000.0]]


In [27]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [31]:
print(x)
print()
print(y)

[[2 44.0 72000.0]
 [0 27.0 48000.0]
 [1 30.0 54000.0]
 [0 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [2 35.0 58000.0]
 [0 38.77777777777778 52000.0]
 [2 48.0 79000.0]
 [1 50.0 83000.0]
 [2 37.0 67000.0]]

[0 1 0 0 1 1 0 1 0 1]


# train_test_split()

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)

In [33]:
print(x_train)

[[1 40.0 63777.77777777778]
 [2 37.0 67000.0]
 [0 27.0 48000.0]
 [0 38.77777777777778 52000.0]
 [2 48.0 79000.0]
 [0 38.0 61000.0]
 [2 44.0 72000.0]
 [2 35.0 58000.0]]


In [34]:
print(x_test)

[[1 30.0 54000.0]
 [1 50.0 83000.0]]


In [35]:
print(y_train)

[1 1 1 0 1 0 0 1]


In [36]:
print(y_test)

[0 0]


# Normalizer(), fit_transform()

In [40]:
sc_x = Normalizer()

In [42]:
x_train = sc_x.fit_transform(x_train)
print(x_train)

[[1.56794394e-05 6.27177577e-04 9.99999803e-01]
 [2.98507417e-05 5.52238722e-04 9.99999847e-01]
 [0.00000000e+00 5.62499911e-04 9.99999842e-01]
 [0.00000000e+00 7.45726288e-04 9.99999722e-01]
 [2.53164510e-05 6.07594824e-04 9.99999815e-01]
 [0.00000000e+00 6.22950699e-04 9.99999806e-01]
 [2.77777726e-05 6.11110997e-04 9.99999813e-01]
 [3.44827523e-05 6.03448166e-04 9.99999817e-01]]


In [43]:
x_test = sc_x.fit_transform(x_test)
print(x_test)

[[1.85185157e-05 5.55555470e-04 9.99999846e-01]
 [1.20481906e-05 6.02409529e-04 9.99999818e-01]]
